config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :users 
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  root "pages#home"
  
  get "/home", to: "pages#home"
  get "/trails", to: "pages#trails"
  get "/account", to: "pages#account"
  
  get "/gardenofthegods", to: "pages#garden"
  get "/sandcanyon", to: "pages#sand"
  get "/ouray", to: "pages#ouray"
  get "/ice", to: "pages#ice"
  get "/manitou", to: "pages#manitou"
  
  get "/emerald", to: "pages#emerald"
  get "/stmary", to: "pages#stmary"
  get "/bierstadt", to: "pages#bierstadt"
  get "/quandary", to: "pages#quandary"
  get "/high", to: "pages#high"
  
  get "/maroon", to: "pages#maroon"
  get "/independence", to: "pages#independence"
  get "/flatiron", to: "pages#flatiron"
  get "/hanging", to: "pages#hanging"
  get "/pulpit", to: "pages#pulpit"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/trails_database.rb
class TrailsDatabase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def trails
  	@trail = TrailsDatabase.all
  end

  def account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<header>
	<div class="container">
	
		<%= image_tag('banner.png',size: "2000x250") %>
		<h1><Center>Welcome Explorer!</Center></h1>
		<nav>
			<ul>
				<li><%= link_to "Home", home_path %></li>
				<li><%= link_to "Trails", trails_path %></li>
				<li class="nav-item">
				   <%= link_to "Sign Out",
				      destroy_user_session_path, method: :delete, class:"
					  nav-link" %>
					  </li>
			    <li class="nav-item">
					<%= link_to "Sign Up",
					  new_user_registration_path, class:"
					  nav-link" %>
				      </li>
				<li class="nav-item">
				   <%= link_to "Sign In",
				      new_user_session_path, class:"
					  nav-link" %>
					  </li>
				<li class="nav-item">
				   <%= link_to "Edit Profile",
				      edit_user_registration_path, class:"
					  nav-link" %>
					  </li>
			</ul>
		</nav>
		
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
  </body>
</html>

app/views/pages/bierstadt.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('bierstadt.png',size: "200x200") %> Mount Bierstadt  </h1></div>
   
   <p>Length : 5 h 10 min avg </p>
   
   <p>Description : with rewarding views around every corner </p>
   
   <h1> <%= image_tag('idaC.png',size: "650x300") %></h1>
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=Guanella Pass Summit, Idaho Springs, CO 80452"
 		allowfullscreen>
	</iframe>
	
	
	<div class="w3-panel w3-round w3-black"><h1> <%= image_tag('bierstadt.png',size: "200x200") %> Current  </h1></div>
  		
  	<h1> <%= image_tag('idaP.png',size: "400x600") %></h1>
  		 
</html>

app/views/pages/emerald.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('emerald.png',size: "200x200") %> Emerald Lake Trail  </h1></div>
   
   <p>Length :1 h 39min avg </p>
   
   <p>Description : Trail that does not allow dogs </p>
   
   <h1> <%= image_tag('estC.png',size: "650x300") %></h1>
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=Bear Lake Rd, Estes Park, CO 80517"
 		allowfullscreen>
	</iframe>
	
	<h1> <%= image_tag('estP.png',size: "400x600") %></h1>
  			 
</html>

app/views/pages/flatiron.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('flat.png',size: "200x200") %> First and Second Flatiorns Loop  </h1></div>
   
   <p>Length :2 h 17min avg </p>
   
   <p>Description : through the Boulder flatirons best traversed during April-October </p>
   
	<h1> <%= image_tag('bolC.png',size: "650x300") %></h1>   
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=Chautauqua, 900 Baseline Rd, Boulder, CO 80302"
 		allowfullscreen>
	</iframe>
	
	<h1> <%= image_tag('bolP.png',size: "400x600") %></h1>
  			 
</html>

app/views/pages/garden.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('garden.png',size: "200x200") %> Garden of The Gods Outer Loop  </h1></div>
   
   <p>Length :2h 37 min avg </p>
   
   <p>Description : loop good for birding, hiking and walking </p>
   
   <h1> <%= image_tag('cosC.png',size: "650x300") %></h1>
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=1805 N 30th St, Colorado Spring, CO 80904, United States"
 		allowfullscreen>
	</iframe>
	
	<h1> <%= image_tag('cosP.png',size: "400x600") %></h1>
  			 
</html>

app/views/pages/hanging.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('hang.png',size: "200x200") %> Hanging Lake Trail”  </h1></div>
   
   <p>Length :2 h 9min avg </p>
   
   <p>Description : straightforward hike requiring permit. Beautiful lake and mountain views </p>
   
	<h1> <%= image_tag('golC.png',size: "650x300") %></h1>   
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=Glenwood Springs, Colorado 81601"
 		allowfullscreen>
	</iframe>
	
	<h1> <%= image_tag('golP.png',size: "400x600") %></h1>
  			 
</html>

app/views/pages/ice.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('ice.png',size: "200x200") %> Ice Lake Basin  </h1></div>
   
   <p>Length :2h 37 min avg </p>
   
   <p>Description : loop good for birding, hiking and walking </p>
   
	<h1> <%= image_tag('golC.png',size: "650x300") %></h1>   
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=37. -773 806, WA-107, Durango, CO 81301"
 		allowfullscreen>
	</iframe>
	
	<h1> <%= image_tag('golP.png',size: "400x600") %></h1>
  			 
</html>

app/views/pages/independence.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('ind.png',size: "200x200") %> Independence Mountain Trail at Pence Park  </h1></div>
   
   <p>Length :1 h 30min avg </p>
   
   <p>Description : straightforward hike offering stunning views of Evergreen and Bear Mountain </p>

	<h1> <%= image_tag('golC.png',size: "650x300") %></h1>     
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=4400 Parmalee Gulch Road Parking, 3940 Myers Gulch Rd, Golden, CO 80401"
 		allowfullscreen>
	</iframe>
  	
  	<h1> <%= image_tag('golP.png',size: "400x600") %></h1>
  			 		 
</html>

app/views/pages/manitou.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('incline.png',size: "200x200") %> The Manitou Incline </h1></div>
   
   <p>Length :3 h 14 min avg </p>
   
   <p>Description : staircase hike boasting beautiful views of Manitou </p>
   
   <h1> <%= image_tag('manC.png',size: "650x300") %></h1>
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=444 Ruxton Ave, Manitou Springs,Colorado"
 		allowfullscreen>
	</iframe>
	
	<h1> <%= image_tag('manP.png',size: "400x600") %></h1>
  			 
</html>

app/views/pages/maroon.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('mar.png',size: "200x200") %> Maroon Bells Scenic Loop Traill  </h1></div>
   
   <p>Length :42min avg </p>
   
   <p>Description : exploration providing an easy path to the beautiful lake </p>
   
	<h1> <%= image_tag('aspC.png',size: "650x300") %></h1>   
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=Aspen 1, CO"
 		allowfullscreen>
	</iframe>
  		
  		
  	<h1> <%= image_tag('aspP.png',size: "400x600") %></h1>	 
</html>

app/views/pages/ouray.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('Ouray.png',size: "200x200") %> Ouray Perimeter Trail  </h1></div>
   
   <p>Length :3 h 19 min avg </p>
   
   <p>Description : hike allowing hikers to explore all of Ouray’s spectacular sights </p>
   
	<h1> <%= image_tag('ourC.png',size: "650x300") %></h1>    
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=perimeter trail trailhead"
 		allowfullscreen>
	</iframe>
  	
  	<h1> <%= image_tag('ourP.png',size: "400x600") %></h1> 
</html>

app/views/pages/pulpit.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('pulpit.png',size: "200x200") %> Pulpit Rock Park Loop  </h1></div>
   
   <p>Length :1 h 47min avg </p>
   
   <p>Description : hike full of wildlife and, at the peak, incredible views of Colorado Springs </p>
   
   <h1> <%= image_tag('cosC.png',size: "650x300") %></h1>  
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=Northeast Colorado Springs, Colorado Springs, CO 80918"
 		allowfullscreen>
	</iframe>
	
	c
  			 
</html>

app/views/pages/quandary.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('quan.png',size: "200x200") %> Quandary Peak Trail  </h1></div>
   
   <p>Length :5h 25min avg </p>
   
   <p>Description : hike with steep elevation climbs and windy/snowy conditions but nonetheless beautiful and rewarding </p>
   
   <h1> <%= image_tag('breC.png',size: "650x300") %></h1>  
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=Quandary Peak Trailhead, Mc Cullough Gulch Rd, Breckenridge, CO 80424"
 		allowfullscreen>
	</iframe>
	
	<h1> <%= image_tag('breC.png',size: "650x300") %></h1>  
  			 
</html>

app/views/pages/sand.html.erb
<!DOCTYPE html>

<html>
   
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    

   <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('sand.png',size: "200x200") %> Sand canyon, Mesa, Greenlee, Red Rock Canyon Loop  </h1></div>
   
   <p>Length :2h 28 min avg </p>
   
   <p>Description : hike with horseback riding, birding and hiking </p>
   
	<h1> <%= image_tag('manC.png',size: "650x300") %></h1>    
   
   <iframe width="500" height="500" frameborder="10" style="border:1"
 		src="https://www.google.com/maps/embed/v1/place?			key=AIzaSyCQKmB2OXd33wOaKQtWTvgEXTTqx-G9eiM&q=199-101 Bevers PI, Manitou Springs, CO 80829, United States"
 		allowfullscreen>
	</iframe>
	
	<h1> <%= image_tag('manC.png',size: "650x300") %></h1> 
  			 
</html>

app/views/pages/trails.html.erb
<!DOCTYPE html>

<html>
   <script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="application.css">
    <%= render "layouts/navbar" %>
    <%= yield %>
    
    <div class="w3-panel w3-round w3-black"><h1> <%= image_tag('pic1.png',size: "200x200") %> Trails in Colorado. </h1></div>
    

    	<table class = "sortable" border: 1px solid;>
    		<tr>
			   <% if user_signed_in? %>
    			<th>Name</th>
        		<th>Address</th>
        		<th>difficulty</th>
        		<th>Activity</th>      
      	</tr>
  			
    		<tr>
      		<td><%= link_to "Garden of the Gods Outer Loop", gardenofthegods_path %></td>
      		<td>1805 N 30th St, Colorado Springs</td>
      		<td>Easy</td>
      		<td>Hiking</td>	
      	</tr>
			
			<tr>
      		<td><%= link_to "Sand canyon, Mesa, Greenlee, Red Rock Canyon Loop" ,sandcanyon_path %> </td>
      		<td> red rock canyon trail </td>
      		<td> moderate </td>
      		<td> Hiking and horseback riding </td>	
      	</tr>
			
			<tr>
      		<td><%= link_to "Ouray Perimeter Trail" ,ouray_path %></td>
      		<td> perimeter trail trailhead </td>
      		<td> Easy </td>
      		<td> Hiking </td>	
      	</tr>
      	
      	<tr>
      		<td><%= link_to "Ice Lake Basin" , ice_path %> </td>
      		<td> Ice Lake Basin </td>
      		<td> Hard </td>
      		<td> Backpacking and Hiking </td>	
      	</tr>
      	
      	<tr>
      		<td><%= link_to "The Manitou Incline" , manitou_path %> </td>
      		<td> 444 Ruxton Ave, Manitou Springs,Colorado </td>
      		<td> Hard </td>
      		<td> Hiking </td>	
      	</tr>
      	<tr>
      		<td><%= link_to "Emerald Lake Trail" , emerald_path %> </td>
      		<td> Bear Lake Rd, Estes Park, CO 80517 </td>
      		<td> Easy </td>
      		<td> Hiking, Snowshoeing </td>	
      	</tr>
      	<tr>
      		<td><%= link_to "St Mary’s Glacier Trailhead" , stmary_path %> </td>
      		<td> St Mary's Glacier Trailhead, St Marys Dr, Idaho Springs, CO 80452 </td>
      		<td> Moderate </td>
      		<td> Hiking, Cross-Country Skiing and Fishing </td>	
      	</tr>
      	<tr>
      		<td><%= link_to "Mount Bierstadt" , bierstadt_path %> </td>
      		<td> Guanella Pass Summit, Idaho Springs, CO 80452 </td>
      		<td> Hard </td>
      		<td> Hiking </td>	
      	</tr>
      	
      	<tr>
      		<td><%= link_to "Quandary Peak Trail" , quandary_path %> </td>
      		<td> Quandary Peak Trailhead, Mc Cullough Gulch Rd, Breckenridge, CO 80424 </td>
      		<td> Hard </td>
      		<td> Hiking and Snowshoeing </td>	
      	</tr>
      	
      	<tr>
      		<td><%= link_to "High Dune Trail" , high_path %> </td>
      		<td> Parking lot, Mosca, CO 81146 </td>
      		<td> Hard </td>
      		<td> Hiking and Camping </td>	
      	</tr>	
			<tr>
      		<td><%= link_to "Maroon Bells Scenic Loop Trail" , maroon_path %> </td>
      		<td> Aspen 1, CO </td>
      		<td> Easy </td>
      		<td> Hiking </td>	
      	</tr>
      	<tr>
      		<td><%= link_to "Independence Mountain Trail at Pence Park" , independence_path %> </td>
      		<td> 4400 Parmalee Gulch Road Parking, 3940 Myers Gulch Rd, Golden, CO 80401 </td>
      		<td> Moderate </td>
      		<td> Hiking and Running </td>	
      	</tr>	
      	<tr>
      		<td><%= link_to "First and Second Flatiorns Loop" , flatiron_path %> </td>
      		<td> Chautauqua, 900 Baseline Rd, Boulder, CO 80302 </td>
      		<td> Moderate </td>
      		<td> Hiking and Rock-Climbing </td>	
      	</tr>  	
      	<tr>
      		<td><%= link_to "Hanging Lake Trail" , hanging_path %> </td>
      		<td> Glenwood Springs, Colorado 81601 </td>
      		<td> Moderate </td>
      		<td> Hiking </td>	
      	</tr>
      	<tr>
      		<td><%= link_to "Pulpit Rock Park Loop" , pulpit_path %> </td>
      		<td> Northeast Colorado Springs, Colorado Springs, CO 80918 </td>
      		<td> Moderate </td>
      		<td> Hiking and Biking </td>	
      	</tr>
		        <% else %> 
		            <h4>Signin to show more information about trails.</h4>
		        <% end %>
</html>